### ISSUE TITLE
[BUG] Two 3DText bugs

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#119] opened 2016-06-02 16:00 UTC
1. Dynamic 3DTexts aren't appearing if you spectate someone. (regular 3DTexts are appearing)

2. Not sure that this is a streamer bug, as I didn't test the regular 3DText attach function: If a player is passenger in your vehicle and you have a big vehicle speed (I tested it with SetVehicleVelocity) the Dynamic 3DText will disappear for a few seconds ocasionally then reappear.

**Comment by Patrik356b** [comment] 2016-06-02 16:45
The second one might be caused by the streaming / draw distance

**Comment by IstuntmanI** [comment] 2016-06-02 18:14
It surely is, but the checks should be modified if it is actually attached to someone.

**Comment by samp-incognito** [comment] 2016-06-03 15:40
> Dynamic 3DTexts aren't appearing if you spectate someone. (regular 3DTexts are appearing)

Are you positive about that? I just think this would have been brought up before, unless it's something that has crept in to one of the newer versions. I don't have any way of testing it right now, but my guess is that it might have something to do with GetPlayerPos not working if the player isn't spawned. You could see if using Streamer_ToggleCameraUpdate has any effect.

> Not sure that this is a streamer bug, as I didn't test the regular 3DText attach function: If a player is passenger in your vehicle and you have a big vehicle speed (I tested it with SetVehicleVelocity) the Dynamic 3DText will disappear for a few seconds ocasionally then reappear.

That would probably have to do with the velocity compensation code. There is an upper limit in place that turns it off if the player/vehicle is moving too fast, but I'm seeing that it's set at 25.0, which, coverting from SA's weird velocity units (about 1/50th of a m/s, apparently), would be a maximum of 1250 m/s. If the average time between updates is, say, 0.25 s, that would offset the player's current position by 312.5,. which probably exceeds the 3D text label's streaming distance.

Anyway, a more sane value is probably around 5.0 to 7.5, but maybe I'll just add some way to configure it or turn it off completely.

**Comment by IstuntmanI** [comment] 2016-06-03 16:34
I tried toggling camera update to on and there's no effect. The thing is that every dynamic checkpoints/objects are being streamed even if it is on or off, there's a problem only with the 3DTexts. Now I saw that some 3DTexts are appearing and some not. Two of them even have two identic codes (just the coordinates are changed): one of them is appearing while the other one doesn't, also, they are close one to eachother. Also, I have one attached Dynamic 3DText to few players and it is always appearing when I spectate them.

Can anyone else confirm it ?

**Comment by Patrik356b** [comment] 2016-06-03 21:39
How is the LOS? (if you're using that)

**Comment by IstuntmanI** [comment] 2016-06-03 22:05
It doesn't matter, it is just some internal SA:MP check so the 3DText won't be there through objects. As I said, I had two 3DTexts each near to eachother, only with their coordinates changed, only one was showing up. By the way, I think that most of (or maybe all) the 3DTexts are using a testLOS of 1.

**Comment by IstuntmanI** [comment] 2016-07-18 15:55
About the first bug, I created a testing command:

```pawn
CMD:text( playerid, params[ ] )
{
	if( sscanf( params, "d", params[ 0 ] ) || !( 0 <= params[ 0 ] <= 13 ) )
		return SendClientMessage( playerid, -1, "/text [type: 0-13]" );

	new Float:X, Float:Y, Float:Z;
	GetPlayerPos( playerid, X, Y, Z );

	switch( params[ 0 ] )
	{
		case 0: CreateDynamic3DTextLabel( "Text 0", -1, X, Y, Z, 2.5, .testlos = 1 );
		case 1: CreateDynamic3DTextLabel( "Text 1", -1, X, Y, Z, 2.5, .testlos = 0 );
		case 2: CreateDynamic3DTextLabel( "Text 2", -1, X, Y, Z, 5.0, .testlos = 1 );
		case 3: CreateDynamic3DTextLabel( "Text 3", -1, X, Y, Z, 5.0, .testlos = 0 );
		case 4: CreateDynamic3DTextLabel( "Text 4", -1, X, Y, Z, 10.0, .testlos = 1 );
		case 5: CreateDynamic3DTextLabel( "Text 5", -1, X, Y, Z, 10.0, .testlos = 0 );
		case 6: CreateDynamic3DTextLabel( "Text 6", -1, X, Y, Z, 15.0, .testlos = 1 );
		case 7: CreateDynamic3DTextLabel( "Text 7", -1, X, Y, Z, 15.0, .testlos = 0 );
		case 8: CreateDynamic3DTextLabel( "Text 8", -1, X, Y, Z, 20.0, .testlos = 1 );
		case 9: CreateDynamic3DTextLabel( "Text 9", -1, X, Y, Z, 20.0, .testlos = 0 );
		case 10: CreateDynamic3DTextLabel( "Text 10", -1, X, Y, Z, 25.0, .testlos = 1 );
		case 11: CreateDynamic3DTextLabel( "Text 11", -1, X, Y, Z, 25.0, .testlos = 0 );
		case 12: CreateDynamic3DTextLabel( "Text 12", -1, X, Y, Z, 30.0, .testlos = 1 );
		case 13: CreateDynamic3DTextLabel( "Text 13", -1, X, Y, Z, 30.0, .testlos = 0 );
	}

	return 1;
}
```
When spectating I see only "Text 10-13" from a pretty good distance (not 25.0+ units anyway) and I also see "Text 8-9" sometimes, only when I get the camera really close. Then I thought that maybe it is a SA:MP bug:

```pawn
CMD:text( playerid, params[ ] )
{
	if( sscanf( params, "d", params[ 0 ] ) || !( 0 <= params[ 0 ] <= 13 ) )
		return SendClientMessage( playerid, -1, "/text [type: 0-13]" );

	new Float:X, Float:Y, Float:Z;
	GetPlayerPos( playerid, X, Y, Z );

	switch( params[ 0 ] )
	{
		case 0: Create3DTextLabel( "Text 0", -1, X, Y, Z, 2.5, 0, .testLOS = 1 );
		case 1: Create3DTextLabel( "Text 1", -1, X, Y, Z, 2.5, 0, .testLOS = 0 );
		case 2: Create3DTextLabel( "Text 2", -1, X, Y, Z, 5.0, 0, .testLOS = 1 );
		case 3: Create3DTextLabel( "Text 3", -1, X, Y, Z, 5.0, 0, .testLOS = 0 );
		case 4: Create3DTextLabel( "Text 4", -1, X, Y, Z, 10.0, 0, .testLOS = 1 );
		case 5: Create3DTextLabel( "Text 5", -1, X, Y, Z, 10.0, 0, .testLOS = 0 );
		case 6: Create3DTextLabel( "Text 6", -1, X, Y, Z, 15.0, 0, .testLOS = 1 );
		case 7: Create3DTextLabel( "Text 7", -1, X, Y, Z, 15.0, 0, .testLOS = 0 );
		case 8: Create3DTextLabel( "Text 8", -1, X, Y, Z, 20.0, 0, .testLOS = 1 );
		case 9: Create3DTextLabel( "Text 9", -1, X, Y, Z, 20.0, 0, .testLOS = 0 );
		case 10: Create3DTextLabel( "Text 10", -1, X, Y, Z, 25.0, 0, .testLOS = 1 );
		case 11: Create3DTextLabel( "Text 11", -1, X, Y, Z, 25.0, 0, .testLOS = 0 );
		case 12: Create3DTextLabel( "Text 12", -1, X, Y, Z, 30.0, 0, .testLOS = 1 );
		case 13: Create3DTextLabel( "Text 13", -1, X, Y, Z, 30.0, 0, .testLOS = 0 );
	}

	return 1;
}
```
exactly the same thing happened. When I'm spectating the draw distance appears to be a lot smaller than the set one. When I'm onfoot I see those 3DTexts from a pretty big distance, the set one.

Lots of 3DTexts in my server aren't being shown when spectating, but now I know it is because I don't have a too big draw distance set for them.

Yet another SA:MP bug.

-------------

Incognito, could you rename the "testlos" parameters (CreateDynamic3DTextLabel(Ex)) to "testLOS" ? "LOS" is uppercase in a_samp.inc and it should be here too.

-------------

If the number 2 won't be fixed (it isn't a big problem anyway) you can close this issue.

**Comment by samp-incognito** [comment] 2016-07-18 23:43
Thanks for verifying that. I can fix the second issue. That's easily done.

> Incognito, could you rename the "testlos" parameters (CreateDynamic3DTextLabel(Ex)) to "testLOS" ? "LOS" is uppercase in a_samp.inc and it should be here too.

There are quite a few other parameters like that too. I believe I decided to change them all to lowercase some time ago to make everything more consistent. Of course, the problem now is that it might break some scripts if they're all changed back.

**Closed** 2016-07-18 23:48 UTC
