### ISSUE TITLE
Invalid Index Parameter

### ISSUE THREAD

**Issue by Xlithan** [samp-incognito/samp-streamer-plugin#375] opened 2021-03-24 01:19 UTC
Just upgraded from an older version of Streamer. Everything compiled ok but I'm getting this issue during server runtime:

[debug] Run time error 20: "Invalid index parameter (bad entry point)"

**Comment by IstuntmanI** [comment] 2021-09-03 04:34
If this is still a problem for you: it may be fixed in a newer version of crashdetect (actually it was [fixed at the end of 2014](https://github.com/Zeex/samp-plugin-crashdetect/releases/tag/v4.15.1), so I pretty much doubt that you are using an even older crashdetect version). If updating crashdetect won't fix your problem, then it may be caused by the combination of plugins you are using. If I remember correctly, similar problems were caused when different plugins were implementing different sampGDK versions. Maybe try updating some other plugins too?

**Comment by Xlithan** [comment] 2021-09-03 08:11
I think I fixed it. Can't remember how but I did.

**Closed** 2022-02-21 00:02 UTC
