### ISSUE TITLE
Server crashed due to an unknown error | #GPR

### ISSUE THREAD

**Issue by FratziWear** [samp-incognito/samp-streamer-plugin#113] opened 2016-05-10 13:28 UTC
Hi, I got this problem on my SA:MP Server. I think is from your streaming, can you check please?

> [19:55:50] [debug] Server crashed due to an unknown error
> [19:55:50] [debug] Native backtrace:
> [19:55:50] [debug] #0 f7484e8b in _ZN10StackTraceC1EPv () from plugins/crashdetect.so
> [19:55:50] [debug] #1 f747dbcf in _ZN11CrashDetect20PrintNativeBacktraceERSoPv () from plugins/crashdetect.so
> [19:55:50] [debug] #2 f747edbc in _ZN11CrashDetect20PrintNativeBacktraceEPv () from plugins/crashdetect.so
> [19:55:50] [debug] #3 f747f226 in _ZN11CrashDetect11OnExceptionEPv () from plugins/crashdetect.so
> [19:55:50] [debug] #4 f7484adc in ?? () from plugins/crashdetect.so
> [19:55:50] [debug] #5 f779f410 in ?? ()
> [19:55:50] [debug] #6 f779f425 in ?? ()
> [19:55:50] [debug] #7 f74d2941 in gsignal () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
> [19:55:50] [debug] #8 f74d5d72 in abort () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
> [19:55:50] [debug] #9 f750ee15 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
> [19:55:50] [debug] #10 f7518f01 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
> [19:55:50] [debug] #11 f751935a in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
> [19:55:50] [debug] #12 f751a6e5 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
> [19:55:50] [debug] #13 f751d81d in cfree () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
> [19:55:50] [debug] #14 f76a54bf in _ZdlPv () from /usr/lib/i386-linux-gnu/libstdc++.so.6
> [19:55:50] [debug] #15 080e2239 in ?? () from samp03svr
> [19:55:50] [debug] #16 f73ea7a3 in ?? () from plugins/streamer.so
> [19:55:50] [debug] #17 f74466a5 in ?? () from plugins/streamer.so
> [19:55:50] [debug] #18 f7448b0a in ?? () from plugins/streamer.so
> [19:55:50] [debug] #19 f7449127 in ?? () from plugins/streamer.so
> [19:55:50] [debug] #20 f7415cc5 in ProcessTick () from plugins/streamer.so
> [19:55:50] [debug] #21 080d1ce2 in ?? () from samp03svr
> [19:55:50] [debug] #22 080aef6c in ?? () from samp03svr
> [19:55:50] [debug] #23 080aa13a in ?? () from samp03svr
> [19:55:50] [debug] #24 f74bee46 in __libc_start_main () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
> [19:55:50] [debug] #25 0804b4e1 in ?? () from samp03svr

Any ideea why!? Thank you.

Best regards,
FratziWear | CEO Founder #GPR

**Comment by samp-incognito** [comment] 2016-05-10 23:52
The streamer plugin is pretty far down in that backtrace. I doubt it has anything to do with this. Also, it looks like `PrintNativeBacktrace` was called by CrashDetect. Perhaps you should see what it printed in your server log?

**Comment by FratziWear** [comment] 2016-05-11 13:44
It can be from CrashDetect? On my serverlog.txt is just this, what you can see. I don't know why or what's happend :|.

**Comment by samp-incognito** [comment] 2016-05-11 17:44
Sorry, I see that is what you posted. I was thinking it was a GDB backtrace for some reason. Well, I can't really do anything with this. If you compiled a debug version of the plugin and ran it with GDB, I'd be able to see what was going on in the plugin at the time if the crash. I think if the plugin were truly causing this, though, it would be further up in the backtrace, so I think it's something else, honestly.

I am closing this. If you can give me more information (I.e., a better backtrace, or steps to reproduce the crash), then I'll reopen it.

**Closed by samp-incognito** 2016-05-11 17:44 UTC

**Comment by FratziWear** [comment] 2016-05-11 18:31
> Started server on 93.119.26.5:7777, with maxplayers: 200 lanmode is OFF.
> 
> *** glibc detected *** /home/gsp_834/93.119.26.5-7777/samp03svr: free(): corrupted unsorted chunks: 0xf557a8c0 ***
> ======= Backtrace: =========
> /lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x70f01)[0xf74e0f01]
> /lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x72768)[0xf74e2768]
> /lib/i386-linux-gnu/i686/cmov/libc.so.6(cfree+0x6d)[0xf74e581d]
> /usr/lib/i386-linux-gnu/libstdc++.so.6(_ZdlPv+0x1f)[0xf766d4bf]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x808013d]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x8074c3a]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x80763fe]
> /lib/i386-linux-gnu/i686/cmov/libpthread.so.0(+0x5c39)[0xf7715c39]
> /lib/i386-linux-gnu/i686/cmov/libc.so.6(clone+0x5e)[0xf754578e]
> ======= Memory map: ========
> 08048000-08095000 r-xp 00000000 08:02 17563655 /home/gsp_834/93.119.26.5-7777/samp03svr
> 08095000-08097000 rwxp 0004d000 08:02 17563655 /home/gsp_834/93.119.26.5-7777/samp03svr
> 08097000-08180000 r-xp 0004f000 08:02 17563655 /home/gsp_834/93.119.26.5-7777/samp03svr
> 08180000-081a2000 rw-p 00138000 08:02 17563655 /home/gsp_834/93.119.26.5-7777/samp03svr
> 081a2000-081cd000 rw-p 00000000 00:00 0
> 09070000-09071000 rw-p 00000000 00:00 0 [heap]
> 09071000-09073000 rwxp 00000000 00:00 0 [heap]
> 09073000-0a506000 rw-p 00000000 00:00 0 [heap]
> f4700000-f4769000 rw-p 00000000 00:00 0
> f4769000-f4800000 ---p 00000000 00:00 0
> f4900000-f4b00000 rw-p 00000000 00:00 0
> f4b00000-f4c00000 rw-p 00000000 00:00 0
> f4c00000-f4ca0000 rw-p 00000000 00:00 0
> f4ca0000-f4d00000 ---p 00000000 00:00 0
> f4d00000-f4f00000 rw-p 00000000 00:00 0
> f4f00000-f5100000 rw-p 00000000 00:00 0
> f5100000-f5200000 rw-p 00000000 00:00 0
> f5200000-f5300000 rw-p 00000000 00:00 0
> f5300000-f5500000 rw-p 00000000 00:00 0
> f5500000-f5700000 rw-p 00000000 00:00 0
> f5700000-f58fb000 rw-p 00000000 00:00 0
> f58fb000-f5900000 ---p 00000000 00:00 0
> f5900000-f5b00000 rw-p 00000000 00:00 0
> f5b00000-f5c00000 rw-p 00000000 00:00 0
> f5cc7000-f6b0f000 rw-p 00000000 00:00 0
> f6b0f000-f6b10000 ---p 00000000 00:00 0
> f6b10000-f7310000 rw-p 00000000 00:00 0
> f7310000-f731a000 r-xp 00000000 08:02 2494078 /lib/i386-linux-gnu/i686/cmov/libnss_files-2.13.so
> f731a000-f731b000 r--p 00009000 08:02 2494078 /lib/i386-linux-gnu/i686/cmov/libnss_files-2.13.so
> f731b000-f731c000 rw-p 0000a000 08:02 2494078 /lib/i386-linux-gnu/i686/cmov/libnss_files-2.13.so
> f732c000-f73c8000 rw-p 00000000 00:00 0
> f73c8000-f73d7000 r-xp 00000000 08:02 17707171 /home/gsp_834/93.119.26.5-7777/plugins/sscanf.so
> f73d7000-f73d8000 rw-p 0000e000 08:02 17707171 /home/gsp_834/93.119.26.5-7777/plugins/sscanf.so
> f73d8000-f73df000 r-xp 00000000 08:02 2494079 /lib/i386-linux-gnu/i686/cmov/librt-2.13.so
> f73df000-f73e0000 r--p 00006000 08:02 2494079 /lib/i386-linux-gnu/i686/cmov/librt-2.13.so
> f73e0000-f73e1000 rw-p 00007000 08:02 2494079 /lib/i386-linux-gnu/i686/cmov/librt-2.13.so
> f73e8000-f746c000 r-xp 00000000 08:02 17694932 /home/gsp_834/93.119.26.5-7777/plugins/streamer.so
> f746c000-f746e000 rw-p 00083000 08:02 17694932 /home/gsp_834/93.119.26.5-7777/plugins/streamer.so
> f7470000-f75cc000 r-xp 00000000 08:02 2494084 /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
> f75cc000-f75cd000 ---p 0015c000 08:02 2494084 /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
> f75cd000-f75cf000 r--p 0015c000 08:02 2494084 /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
> f75cf000-f75d0000 rw-p 0015e000 08:02 2494084 /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
> f75d0000-f75d3000 rw-p 00000000 00:00 0
> f75d8000-f75f4000 r-xp 00000000 08:02 2493965 /lib/i386-linux-gnu/libgcc_s.so.1
> f75f4000-f75f5000 rw-p 0001b000 08:02 2493965 /lib/i386-linux-gnu/libgcc_s.so.1
> f75f8000-f761c000 r-xp 00000000 08:02 2494081 /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
> f761c000-f761d000 r--p 00023000 08:02 2494081 /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
> f761d000-f761e000 rw-p 00024000 08:02 2494081 /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
> f7620000-f7700000 r-xp 00000000 08:02 11671395 /usr/lib/i386-linux-gnu/libstdc++.so.6.0.17
> f7700000-f7704000 r--p 000e0000 08:02 11671395 /usr/lib/i386-linux-gnu/libstdc++.so.6.0.17
> f7704000-f7705000 rw-p 000e4000 08:02 11671395 /usr/lib/i386-linux-gnu/libstdc++.so.6.0.17
> f7705000-f770c000 rw-p 00000000 00:00 0
> f7710000-f7725000 r-xp 00000000 08:02 2494074 /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
> f7725000-f7726000 r--p 00014000 08:02 2494074 /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
> f7726000-f7727000 rw-p 00015000 08:02 2494074 /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
> f7727000-f7729000 rw-p 00000000 00:00 0
> f7730000-f7732000 r-xp 00000000 08:02 2494077 /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
> f7732000-f7733000 r--p 00001000 08:02 2494077 /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
> f7733000-f7734000 rw-p 00002000 08:02 2494077 /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
> f7740000-f7742000 r-xp 00000000 08:02 17704099 /home/gsp_834/93.119.26.5-7777/plugins/nativechecker.so
> f7742000-f7743000 r--p 00001000 08:02 17704099 /home/gsp_834/93.119.26.5-7777/plugins/nativechecker.so
> f7743000-f7744000 rw-p 00002000 08:02 17704099 /home/gsp_834/93.119.26.5-7777/plugins/nativechecker.so
> f7744000-f7748000 rw-p 00000000 00:00 0
> f7748000-f7764000 r-xp 00000000 08:02 2493984 /lib/i386-linux-gnu/ld-2.13.so
> f7764000-f7765000 r--p 0001b000 08:02 2493984 /lib/i386-linux-gnu/ld-2.13.so
> f7765000-f7766000 rw-p 0001c000 08:02 2493984 /lib/i386-linux-gnu/ld-2.13.so
> f7766000-f776a000 rw-p 00000000 00:00 0
> f776a000-f776b000 r-xp 00000000 00:00 0 [vdso]
> ffde6000-ffe07000 rw-p 00000000 00:00 0 [stack]
> /usr/local/games/samp-run.v2.sh: line 116: 1855 Aborted $WORKINGDIR/samp03svr
> [Wed May 11 21:13:53 EEST 2016] SERVICE CRASH, waiting 10 seconds
> [Wed May 11 21:14:03 EEST 2016] SERVICE STARTUP (4/15)
> 
> Started server on 93.119.26.5:7777, with maxplayers: 200 lanmode is OFF.
> 
> *** glibc detected *** /home/gsp_834/93.119.26.5-7777/samp03svr: malloc(): memory corruption: 0xf7640308 ***
> ======= Backtrace: =========
> /lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x70f01)[0xf7550f01]
> /lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x73ce4)[0xf7553ce4]
> /lib/i386-linux-gnu/i686/cmov/libc.so.6(__libc_malloc+0x5c)[0xf75558ec]
> /usr/lib/i386-linux-gnu/libstdc++.so.6(_Znwj+0x25)[0xf76df7b5]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x806eb03]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x807bba8]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x8071b43]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x807c193]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x806d61f]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x807c30f]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x80ac299]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x814abd6]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x80e426f]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x8096a07]
> plugins/streamer.so(+0x888a)[0xf746088a]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x80ebc05]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x80af03c]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x80aa13a]
> /lib/i386-linux-gnu/i686/cmov/libc.so.6(__libc_start_main+0xe6)[0xf74f6e46]
> /home/gsp_834/93.119.26.5-7777/samp03svr[0x804b4e1]
> ======= Memory map: ========
> 08048000-08095000 r-xp 00000000 08:02 17563655 /home/gsp_834/93.119.26.5-7777/samp03svr
> 08095000-08097000 rwxp 0004d000 08:02 17563655 /home/gsp_834/93.119.26.5-7777/samp03svr
> 08097000-08180000 r-xp 0004f000 08:02 17563655 /home/gsp_834/93.119.26.5-7777/samp03svr
> 08180000-081a2000 rw-p 00138000 08:02 17563655 /home/gsp_834/93.119.26.5-7777/samp03svr
> 081a2000-081cd000 rw-p 00000000 00:00 0
> 09317000-09318000 rw-p 00000000 00:00 0 [heap]
> 09318000-0931a000 rwxp 00000000 00:00 0 [heap]
> 0931a000-0a5fa000 rw-p 00000000 00:00 0 [heap]
> f4a00000-f4ac2000 rw-p 00000000 00:00 0
> f4ac2000-f4b00000 ---p 00000000 00:00 0
> f4c00000-f4e00000 rw-p 00000000 00:00 0
> f4e00000-f5000000 rw-p 00000000 00:00 0
> f5000000-f503a000 rw-p 00000000 00:00 0
> f503a000-f5100000 ---p 00000000 00:00 0
> f5100000-f5200000 rw-p 00000000 00:00 0
> f5200000-f53fd000 rw-p 00000000 00:00 0
> f53fd000-f5400000 ---p 00000000 00:00 0
> f5400000-f5600000 rw-p 00000000 00:00 0
> f5600000-f5800000 rw-p 00000000 00:00 0
> f5800000-f5a00000 rw-p 00000000 00:00 0
> f5a00000-f5c00000 rw-p 00000000 00:00 0
> f5c00000-f5cff000 rw-p 00000000 00:00 0
> f5cff000-f5d00000 ---p 00000000 00:00 0
> f5d3f000-f6b87000 rw-p 00000000 00:00 0
> f6b87000-f6b88000 ---p 00000000 00:00 0
> f6b88000-f7388000 rw-p 00000000 00:00 0
> f7388000-f7392000 r-xp 00000000 08:02 2494078 /lib/i386-linux-gnu/i686/cmov/libnss_files-2.13.so
> f7392000-f7393000 r--p 00009000 08:02 2494078 /lib/i386-linux-gnu/i686/cmov/libnss_files-2.13.so
> f7393000-f7394000 rw-p 0000a000 08:02 2494078 /lib/i386-linux-gnu/i686/cmov/libnss_files-2.13.so
> f73a4000-f7440000 rw-p 00000000 00:00 0
> f7440000-f7442000 r-xp 00000000 08:02 17704099 /home/gsp_834/93.119.26.5-7777/plugins/nativechecker.so
> f7442000-f7443000 r--p 00001000 08:02 17704099 /home/gsp_834/93.119.26.5-7777/plugins/nativechecker.so
> f7443000-f7444000 rw-p 00002000 08:02 17704099 /home/gsp_834/93.119.26.5-7777/plugins/nativechecker.so
> f7448000-f7457000 r-xp 00000000 08:02 17707171 /home/gsp_834/93.119.26.5-7777/plugins/sscanf.so
> f7457000-f7458000 rw-p 0000e000 08:02 17707171 /home/gsp_834/93.119.26.5-7777/plugins/sscanf.so
> f7458000-f74dc000 r-xp 00000000 08:02 17694932 /home/gsp_834/93.119.26.5-7777/plugins/streamer.so
> f74dc000-f74de000 rw-p 00083000 08:02 17694932 /home/gsp_834/93.119.26.5-7777/plugins/streamer.so
> f74e0000-f763c000 r-xp 00000000 08:02 2494084 /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
> f763c000-f763d000 ---p 0015c000 08:02 2494084 /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
> f763d000-f763f000 r--p 0015c000 08:02 2494084 /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
> f763f000-f7640000 rw-p 0015e000 08:02 2494084 /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
> f7640000-f7643000 rw-p 00000000 00:00 0
> f7648000-f7664000 r-xp 00000000 08:02 2493965 /lib/i386-linux-gnu/libgcc_s.so.1
> f7664000-f7665000 rw-p 0001b000 08:02 2493965 /lib/i386-linux-gnu/libgcc_s.so.1
> f7668000-f768c000 r-xp 00000000 08:02 2494081 /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
> f768c000-f768d000 r--p 00023000 08:02 2494081 /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
> f768d000-f768e000 rw-p 00024000 08:02 2494081 /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
> f7690000-f7770000 r-xp 00000000 08:02 11671395 /usr/lib/i386-linux-gnu/libstdc++.so.6.0.17
> f7770000-f7774000 r--p 000e0000 08:02 11671395 /usr/lib/i386-linux-gnu/libstdc++.so.6.0.17
> f7774000-f7775000 rw-p 000e4000 08:02 11671395 /usr/lib/i386-linux-gnu/libstdc++.so.6.0.17
> f7775000-f777c000 rw-p 00000000 00:00 0
> f7780000-f7795000 r-xp 00000000 08:02 2494074 /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
> f7795000-f7796000 r--p 00014000 08:02 2494074 /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
> f7796000-f7797000 rw-p 00015000 08:02 2494074 /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
> f7797000-f7799000 rw-p 00000000 00:00 0
> f77a0000-f77a2000 r-xp 00000000 08:02 2494077 /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
> f77a2000-f77a3000 r--p 00001000 08:02 2494077 /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
> f77a3000-f77a4000 rw-p 00002000 08:02 2494077 /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
> f77a5000-f77a8000 rw-p 00000000 00:00 0
> f77a8000-f77af000 r-xp 00000000 08:02 2494079 /lib/i386-linux-gnu/i686/cmov/librt-2.13.so
> f77af000-f77b0000 r--p 00006000 08:02 2494079 /lib/i386-linux-gnu/i686/cmov/librt-2.13.so
> f77b0000-f77b1000 rw-p 00007000 08:02 2494079 /lib/i386-linux-gnu/i686/cmov/librt-2.13.so
> f77b2000-f77b7000 rw-p 00000000 00:00 0
> f77b7000-f77b8000 r-xp 00000000 00:00 0 [vdso]
> f77b8000-f77d4000 r-xp 00000000 08:02 2493984 /lib/i386-linux-gnu/ld-2.13.so
> f77d4000-f77d5000 r--p 0001b000 08:02 2493984 /lib/i386-linux-gnu/ld-2.13.so
> f77d5000-f77d6000 rw-p 0001c000 08:02 2493984 /lib/i386-linux-gnu/ld-2.13.so
> fffa9000-fffca000 rw-p 00000000 00:00 0 [stack]
> /usr/local/games/samp-run.v2.sh: line 116: 1234 Aborted $WORKINGDIR/samp03svr
> [Wed May 11 21:26:52 EEST 2016] SERVICE CRASH, waiting 10 seconds
> [Wed May 11 21:27:02 EEST 2016] SERVICE STARTUP (5/15)
> 
> Started server on 93.119.26.5:7777, with maxplayers: 200 lanmode is OFF.
