### ISSUE TITLE
OnPlayerLeaveDynamicArea - Infinite loop [UPDATE]

### ISSUE THREAD

**Issue by spmn** [samp-incognito/samp-streamer-plugin#62] opened 2015-07-11 14:54 UTC
I've logged all OnPlayerLeaveDynamicArea calls and I found a pattern: right before parameters goes crazy, there is always atleast one call of OnPlayerLeaveDynamicArea with areaid = 73. Areas ID 1-72 are static, so they are created at script init and they aren't destroyed during runtime. All areas whose ID is greater than or equal to 73 are dynamically created and destroyed. Those areas could be destroyed using a command (no such command was typed so this hadn't triggered callback), by player disconnect (no player disconnected, so this hadn't triggered callback) or by OnPlayerLeaveDynamicArea itself (this could have happened). So, when a player exits an area, it is automatically destroyed. IIRC, I started to experience this bug after I switched to v2.7.4. I assume that that fb291f0 (and maybe 038ee90) has (have) something to do with my problem.

Since my mode uses some things added in v2.7.4+, could you provide me linux binaries of the latest streamer version without those commits, so I won't have to downgrade?

Old issue: #60

**Comment by samp-incognito** [comment] 2015-07-11 15:31
Do you have an array somewhere that's using the area IDs as an index? If so, perhaps you could check if the area ID might ever exceed the size of the array?

fb291f0 alone shouldn't cause this problem. OnPlayerLeaveDynamicArea might be called when the area is destroyed, but it's not really destroyed until the callback being executed goes out of scope. If that weren't the case, the plugin would just instantly crash due to an iterator being invalidated, which would happen well before the script could access an invalid index in an array.

038ee90 just made any OnPlayerLeaveDynamicArea callbacks execute before any OnPlayerEnterDynamicArea callbacks. (However, looking at that now, I suppose it would be possible for someone to destroy areas in OnPlayerLeaveDynamicArea that might be used immediately after in OnPlayerEnterDynamicArea. That would be an exceptionally rare case, though, and it wouldn't help your specific situation, but I'll add checks to prevent this later.)

**Comment by spmn** [comment] 2015-07-11 20:00
Yes, after I started to experience this crash I added sanity checks at both enter and exit area, but they didn't helped. However, I want to make sure that those commits are not the source of problem, so I'll try to compile a version without them.

**Comment by spmn** [comment] 2015-07-13 17:44
I forgot to mention that if I increase memory allocated for script via ``#pragma dynamic``, number of invalid OnPlayerLeaveDynamicArea calls and time until server crashes increase too. (time increased from 1 minute to 7-8 minutes)

I managed to compile latest version of streamer [from repo; not releases page] without those two commits. I've been running it for two days and no crash occured.

**Comment by samp-incognito** [comment] 2015-07-15 22:25
I was actually wrong about what I said about fb291f0. The area gets destroyed before the callback is executed. Still, the only thing it's doing is putting the area ID and player ID in a queue. The plugin isn't causing the server to crash. Your script is doing that by accessing an invalid index in an array. You must have an array somewhere that doesn't have proper bounds checking. There's literally no other explanation for this behavior. Unless you can find a way to reproduce it, there's nothing I can do to fix this, because I can't find anything logically wrong with the code.

**Comment by samp-incognito** [comment] 2015-08-03 00:46
You might see if v2.7.8 fixes this. A bug with area callbacks was fixed for #66.

**Comment by samp-incognito** [comment] 2015-08-07 23:48
I'm closing this for now. If you have any new information (as in, a way to reproduce this), then just open a new issue.

**Closed by samp-incognito** 2015-08-07 23:48 UTC
